### ISSUE TITLE
There is no need for the modified papirus-folders script now

### ISSUE THREAD

**Issue by Vibhav201** [xelser/edge-papirus-folders#1]
Hey, you can remove the modified papirus-folders script from your repos. You can just copy the icon files and the original script now autodetects the folder icon themes. Check [this](https://github.com/PapirusDevelopmentTeam/papirus-folders/issues/31).

It works flawlessly, I even got mine added officially - [Dracula Papirus Folders](https://github.com/dracula/papirus-folders).

:)

**Comment by xelser** [comment]
alright, thanks for the heads up 👍🏼
